lib_LTLIBRARIES = libbtvendorhal.la
libbtvendorhal_la_SOURCES = hardware.cc
libbtvendorhal_la_CFLAGS = -DLINUX_ENABLED -fpermissive
libbtvendorhal_la_CFLAGS += -I${BT_INC_PATH}/include
libbtvendorhal_la_CFLAGS += -Iinclude
libbtvendorhal_la_CPPFLAGS = -DLINUX_ENABLED -fpermissive -D__GLIBC__
libbtvendorhal_la_CPPFLAGS += -I${BT_INC_PATH}/include
libbtvendorhal_la_CPPFLAGS += -I${BT_INC_PATH}
libbtvendorhal_la_CPPFLAGS += -I${BT_INC_PATH}/osi
libbtvendorhal_la_CPPFLAGS += -Iinclude
libbtvendorhal_la_LDFLAGS = -ldl -D__GLIBC__  -version-number @LT_VERSION_NUMBER@
