lib_LTLIBRARIES = libbtvendorhal.la
libbtvendorhal_la_SOURCES = hardware.cc
libbtvendorhal_la_CFLAGS = -DLINUX_ENABLED -fpermissive
libbtvendorhal_la_CFLAGS += -I${BT_SOURCE}/stack/system/bt/include
libbtvendorhal_la_CFLAGS += -I${BT_SOURCE}/bt_audio/hal/include
libbtvendorhal_la_CPPFLAGS = -DLINUX_ENABLED -fpermissive -D__GLIBC__
libbtvendorhal_la_CPPFLAGS += -I${BT_SOURCE}/stack/system/bt/include
libbtvendorhal_la_CPPFLAGS += -I${BT_SOURCE}/stack/system/bt
libbtvendorhal_la_CPPFLAGS += -I${BT_SOURCE}/btapp/bt-app/osi
libbtvendorhal_la_CPPFLAGS += -I${BT_SOURCE}/bt_audio/hal/include
libbtvendorhal_la_LDFLAGS = -ldl -D__GLIBC__
