#BT
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_QCOM := true
BOARD_HAS_BT_XPAN  ?= true

#FM
ifneq ($(TARGET_BOARD_TYPE),auto)
BOARD_HAVE_QCOM_FM := true
endif

ifeq ($(TARGET_IS_QLMD), true)
BOARD_HAVE_QCOM_FM := false
endif #TARGET_IS_QLMD

ifeq ($(TARGET_USES_QMAA),true)
ifneq ($(TARGET_USES_QMAA_OVERRIDE_BLUETOOTH),true)
BOARD_ANT_WIRELESS_DEVICE :=
endif
ifneq ($(TARGET_USES_QMAA_OVERRIDE_FM),true)
BOARD_HAVE_QCOM_FM := false
endif
endif
